### ISSUE TITLE
How to scrape 10 profiles every page ?

### ISSUE THREAD

**Issue by bomb1000** [vasin-peach/linkedin-profile-scraper#2]
Hi,

This scraper is really powerful and useful, it helps me a lot. Nevertheless, I'm not acquainted with python. I want to scrape 10 profiles from a page, which means to scrape all the profiles on every page, while the original code only scrape 5 profiles and then get straight to the next page.  Could you please tell me which part of the code should I change? Thanks a lot !

**Comment by vasin-peach** [comment]
I didn't limit the profiles per page. Normally, It should scrap all profiles no matter how many there are.

![image](https://user-images.githubusercontent.com/26850146/88081340-71a8fb00-cbaa-11ea-8f98-6f20ef976edc.png)

**Comment by bomb1000** [comment]
this is what page 11 looks like:
<img width="1440" alt="螢幕快照 2020-07-22 上午2 20 25" src="https://user-images.githubusercontent.com/56310875/88094375-09681280-cbc6-11ea-9228-9d49e86f1ba5.png">

<img width="1440" alt="螢幕快照 2020-07-22 上午2 34 42" src="https://user-images.githubusercontent.com/56310875/88094512-4a602700-cbc6-11ea-90b6-7055cc5b1d67.png">


this is page 12 :

<img width="1440" alt="螢幕快照 2020-07-22 上午2 36 26" src="https://user-images.githubusercontent.com/56310875/88094640-7bd8f280-cbc6-11ea-9f6f-1dc791ffd07a.png">
 

the outcome of scraping page 11 and 12:
<img width="1440" alt="螢幕快照 2020-07-22 上午2 41 13" src="https://user-images.githubusercontent.com/56310875/88094724-9f9c3880-cbc6-11ea-8685-985b5a6ce547.png">

the scraped data:

[02-13-09-22-07-20.json.zip](https://github.com/vasin-peach/linkedin-profile-scraper/files/4955616/02-13-09-22-07-20.json.zip)


<img width="1440" alt="螢幕快照 2020-07-22 上午2 56 10" src="https://user-images.githubusercontent.com/56310875/88095116-2e10ba00-cbc7-11ea-8e0a-bd236a998842.png">

I think I miss somthing ignorantly. 
Thanks for helping !

**Comment by vasin-peach** [comment]
I have pushed laster fix to master now. 
The problem is LinkedIn not loading all profiles at once. We need to scroll down to make the page fetch more profiles than we can scrap that.

[6d3b36d ](https://github.com/vasin-peach/linkedin-profile-scraper/commit/95421d631118a9a59762aba223e73e62719e9774)
